### ISSUE TITLE
Entity is already registered with Engine

### ISSUE THREAD

**Issue by ForsakenHarmony** [libgdx/ashley#226] opened 2016-06-30 18:21 UTC
Getting this error using the pooled engine

Only registering it once in the method it's created

https://github.com/ForsakenHarmony/GameProt/blob/master/core/src/forsakenharmony/gameprot/weapons/Gun.kt#L56

**Comment by saltares** [comment] 2016-07-01 07:15
Are you able to create a unit test that highlights this issue? It would be quite hard for anybody to read and understand your project and pinpoint the issue.

A failing unit test would be most helpful. It could be related to #214.

**Comment by ForsakenHarmony** [comment] 2016-07-01 17:03
The thing is I have no idea why it happens and how it can happen

**Comment by saltares** [comment] 2016-07-03 19:07
Did you see issue #214? There could be issues when removing and then adding entities in the same frame when using a `PooledEngine`.

**Comment by ForsakenHarmony** [comment] 2016-07-05 23:45
Well yes, that seems to be the problem, I "fixed" it doing this
```
fun createEntity(): Entity {
  var entity = engine.createEntity()
  while (entity.flags != 0) {
    entity = engine.createEntity()
  }
  entity.flags = entityID++
  return entity
}
```

Maybe a `PooledEngine#has(entity)` should be added

**Comment by saltares** [comment] 2016-07-06 07:17
I will close this for now as this is a known issue and duplicate of others already in the tracker. Thanks for reporting!

**Closed by saltares** 2016-07-06 07:17 UTC
